In [80]:
import pandas as pd
import numpy as np
import tensorflow as tf
import sklearn
import scikeras


In [81]:
from tensorflow.keras.models import Sequential  # type: ignore
from tensorflow.keras.layers import Dense # type: ignore
from tensorflow.keras import utils as np_utils # type: ignore
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [82]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
iris = fetch_ucirepo(id=53) 
  
# data (as pandas dataframes) 
X = iris.data.features 
y = iris.data.targets 
  
# metadata 
print(iris.metadata) 
  
# variable information 
print(iris.variables)


{'uci_id': 53, 'name': 'Iris', 'repository_url': 'https://archive.ics.uci.edu/dataset/53/iris', 'data_url': 'https://archive.ics.uci.edu/static/public/53/data.csv', 'abstract': 'A small classic dataset from Fisher, 1936. One of the earliest known datasets used for evaluating classification methods.\n', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 150, 'num_features': 4, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1936, 'last_updated': 'Tue Sep 12 2023', 'dataset_doi': '10.24432/C56C76', 'creators': ['R. A. Fisher'], 'intro_paper': {'title': 'The Iris data set: In search of the source of virginica', 'authors': 'A. Unwin, K. Kleinman', 'published_in': 'Significance, 2021', 'year': 2021, 'url': 'https://www.semanticscholar.org/paper/4599862ea877863669a6a8e63a3c707a787d5d7e', 'doi': '1740-9713.01589'}, 'add

In [83]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
y = np_utils.to_categorical(y)
y

c:\Users\wilso\AppData\Local\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [84]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [85]:
neural_network = Sequential([
    tf.keras.layers.InputLayer(shape=(4,)),
    tf.keras.layers.Dense(units=16, activation='tanh',  kernel_initializer='glorot_normal'),
    tf.keras.layers.Dense(units=16, activation='tanh',  kernel_initializer='glorot_normal'),
    tf.keras.layers.Dense(units=3, activation='softmax')
    ])


In [86]:
neural_network.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [87]:
neural_network.fit(X_train, y_train, batch_size=20, epochs=100)

Epoch 1/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - categorical_accuracy: 0.2850 - loss: 1.4505
Epoch 2/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3674 - loss: 1.0741 
Epoch 3/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.6580 - loss: 1.0421 
Epoch 4/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.6624 - loss: 0.9213 
Epoch 5/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.6531 - loss: 0.8614 
Epoch 6/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.8197 - loss: 0.8214 
Epoch 7/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.8590 - loss: 0.7898 
Epoch 8/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.8860 - loss: 0.7466 
Epoch 9/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.8746 - loss: 0.7102 
Epoch 10/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.8403 - loss: 0.6944 
Epoch 11/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s

In [88]:
X

sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [109]:
new = np.array([5.1, 2.6, 2.8, 2.1])

In [110]:
new = np.expand_dims(new, axis=0)

In [111]:
new.size, new.shape

(4, (1, 4))

In [112]:
prevision = neural_network.predict(new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step


In [113]:
prevision

array([[0.02920518, 0.7805495 , 0.1902453 ]], dtype=float32)

In [114]:
prevision = prevision > 0.7
print(prevision)

[[False  True False]]


In [115]:
prevision = neural_network.predict(new)

classe_predita = np.argmax(prevision, axis=1)

classe_predita_nome = label_encoder.inverse_transform(classe_predita)

print(classe_predita_nome[0])


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
Iris-versicolor


In [100]:
# Salvar a estrutura da rede neural no formato JSON
model_json = neural_network.to_json()
with open("iris_struct.json", "w") as json_file:
    json_file.write(model_json)

# Salvar os pesos da rede neural no formato HDF5
neural_network.save_weights("iris_pesos.weights.h5")


In [103]:
# Carregar a estrutura do modelo a partir do JSON
with open('iris_struct.json', 'r') as json_file:
    model_json = json_file.read()

# Recriar o modelo
neural_network_new = tf.keras.models.model_from_json(model_json)

# Carregar os pesos no modelo recriado
neural_network_new.load_weights('iris_pesos.weights.h5')

In [104]:
neural_network_new.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_20 (Dense)                │ (None, 16)             │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_22 (Dense)                │ (None, 3)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,211 (4.73 KB)

 Trainable params: 403 (1.57 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 808 (3.16 KB)

In [105]:
neural_network_new.predict(new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 244ms/step


array([[0.53534234, 0.46176076, 0.00289696]], dtype=float32)