In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import pickle

In [2]:
with open('../data/credit.pkl', 'rb') as f:
  X_credit_treinamento, y_credit_treinamento, X_credit_teste, y_credit_teste = pickle.load(f)

In [3]:
X_credit = np.concatenate((X_credit_treinamento, X_credit_teste), axis = 0)
y_credit = np.concatenate((y_credit_treinamento, y_credit_teste), axis = 0)

In [4]:
rede_neural = pickle.load(open('../data/saved/rede_neural_finalizado.sav', 'rb'))
arvore = pickle.load(open('../data/saved/arvore_finalizado.sav', 'rb'))
svm = pickle.load(open('../data/saved/svm_finalizado.sav', 'rb'))

In [5]:
novo_registro = X_credit[1999]
novo_registro

array([-1.03572293, -0.93978122,  0.04244312])

In [6]:
novo_registro.shape

(3,)

In [7]:
novo_registro = novo_registro.reshape(1, -1)
novo_registro.shape

(1, 3)

In [8]:
novo_registro

array([[-1.03572293, -0.93978122,  0.04244312]])

In [9]:
rede_neural.predict(novo_registro)

array([1], dtype=int64)

In [10]:
arvore.predict(novo_registro)

array([1], dtype=int64)

In [11]:
svm.predict(novo_registro)

array([1], dtype=int64)