In [2]:
!pip install ucimlrepo

In [3]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
breast_cancer_wisconsin_diagnostic = fetch_ucirepo(id=17)

# data (as pandas dataframes)
X = breast_cancer_wisconsin_diagnostic.data.features
y = breast_cancer_wisconsin_diagnostic.data.targets

# metadata
print(breast_cancer_wisconsin_diagnostic.metadata)

# variable information
print(breast_cancer_wisconsin_diagnostic.variables)


{'uci_id': 17, 'name': 'Breast Cancer Wisconsin (Diagnostic)', 'repository_url': 'https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic', 'data_url': 'https://archive.ics.uci.edu/static/public/17/data.csv', 'abstract': 'Diagnostic Wisconsin Breast Cancer Database.', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 569, 'num_features': 30, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['Diagnosis'], 'index_col': ['ID'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1993, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C5DW2B', 'creators': ['William Wolberg', 'Olvi Mangasarian', 'Nick Street', 'W. Street'], 'intro_paper': {'title': 'Nuclear feature extraction for breast tumor diagnosis', 'authors': 'W. Street, W. Wolberg, O. Mangasarian', 'published_in': 'Electronic imaging', 'year': 1993, 'url': 'https://www.semanticscholar.org/paper/53

In [4]:
import pandas as pd

In [5]:
# previsores
X = pd.DataFrame(X)
X

radius1  texture1  perimeter1   area1  smoothness1  compactness1  \
0      17.99     10.38      122.80  1001.0      0.11840       0.27760   
1      20.57     17.77      132.90  1326.0      0.08474       0.07864   
2      19.69     21.25      130.00  1203.0      0.10960       0.15990   
3      11.42     20.38       77.58   386.1      0.14250       0.28390   
4      20.29     14.34      135.10  1297.0      0.10030       0.13280   
..       ...       ...         ...     ...          ...           ...   
564    21.56     22.39      142.00  1479.0      0.11100       0.11590   
565    20.13     28.25      131.20  1261.0      0.09780       0.10340   
566    16.60     28.08      108.30   858.1      0.08455       0.10230   
567    20.60     29.33      140.10  1265.0      0.11780       0.27700   
568     7.76     24.54       47.92   181.0      0.05263       0.04362   

     concavity1  concave_points1  symmetry1  fractal_dimension1  ...  radius3  \
0       0.30010          0.14710     0.2419             0.07871  ...   25.380   
1       0.08690          0.07017     0.1812             0.05667  ...   24.990   
2       0.19740          0.12790     0.2069             0.05999  ...   23.570   
3       0.24140          0.10520     0.2597             0.09744  ...   14.910   
4       0.19800          0.10430     0.1809             0.05883  ...   22.540   
..          ...              ...        ...                 ...  ...      ...   
564     0.24390          0.13890     0.1726             0.05623  ...   25.450   
565     0.14400          0.09791     0.1752             0.05533  ...   23.690   
566     0.09251          0.05302     0.1590             0.05648  ...   18.980   
567     0.35140          0.15200     0.2397             0.07016  ...   25.740   
568     0.00000          0.00000     0.1587             0.05884  ...    9.456   

     texture3  perimeter3   area3  smoothness3  compactness3  concavity3  \
0       17.33      184.60  2019.0      0.16220       0.66560      0.7119   
1       23.41      158.80  1956.0      0.12380       0.18660      0.2416   
2       25.53      152.50  1709.0      0.14440       0.42450      0.4504   
3       26.50       98.87   567.7      0.20980       0.86630      0.6869   
4       16.67      152.20  1575.0      0.13740       0.20500      0.4000   
..        ...         ...     ...          ...           ...         ...   
564     26.40      166.10  2027.0      0.14100       0.21130      0.4107   
565     38.25      155.00  1731.0      0.11660       0.19220      0.3215   
566     34.12      126.70  1124.0      0.11390       0.30940      0.3403   
567     39.42      184.60  1821.0      0.16500       0.86810      0.9387   
568     30.37       59.16   268.6      0.08996       0.06444      0.0000   

     concave_points3  symmetry3  fractal_dimension3  
0             0.2654     0.4601             0.11890  
1             0.1860     0.2750             0.08902  
2             0.2430     0.3613             0.08758  
3             0.2575     0.6638             0.17300  
4             0.1625     0.2364             0.07678  
..               ...        ...                 ...  
564           0.2216     0.2060             0.07115  
565           0.1628     0.2572             0.06637  
566           0.1418     0.2218             0.07820  
567           0.2650     0.4087             0.12400  
568           0.0000     0.2871             0.07039  

[569 rows x 30 columns]

In [6]:
# classe
y = pd.DataFrame(y)
y

Diagnosis
0           M
1           M
2           M
3           M
4           M
..        ...
564         M
565         M
566         M
567         M
568         B

[569 rows x 1 columns]

In [7]:
import sklearn
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [9]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((426, 30), (143, 30), (426, 1), (143, 1))

In [10]:
import tensorflow as tf
from tensorflow.keras.models import Sequential

In [11]:
neural_network = Sequential([
    tf.keras.layers.InputLayer(shape = (30,)),
    tf.keras.layers.Dense(units=16, activation='relu', kernel_initializer='random_uniform'),
    tf.keras.layers.Dense(units=16, activation='relu', kernel_initializer='random_uniform'),
    tf.keras.layers.Dense(units=1, activation='sigmoid')
])

In [12]:
neural_network.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 16)                  │             496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 16)                  │             272 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001, clipvalue = 0.5)

In [14]:
neural_network.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['binary_accuracy'])

In [15]:
# Verifique se os dados de y estão em formato string
print(y_train.dtypes)

# Se as classes forem strings, converta-as para numérico
y_train = y_train.replace({'M': 1, 'B': 0})
y_test = y_test.replace({'M': 1, 'B': 0})

# Verifique o tipo de dados após a conversão
print(y_train.dtypes)


Diagnosis    object
dtype: object
Diagnosis    int64
dtype: object


In [16]:
neural_network.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - binary_accuracy: 0.4623 - loss: 0.8385
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.6550 - loss: 0.6057
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - binary_accuracy: 0.8146 - loss: 0.5106
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.8987 - loss: 0.3692
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - binary_accuracy: 0.8848 - loss: 0.3175
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.9028 - loss: 0.2678
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.8884 - loss: 0.2793
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.8733 - loss: 0.2785
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8916 - loss: 0.2523
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.9201 - loss: 0.2134
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.9135 -

In [17]:
pesos0 = neural_network.layers[0].get_weights()
pesos0

[array([[-3.26582342e-02, -2.87223198e-02, -4.82142828e-02,
          1.92571133e-02,  3.85963283e-02,  1.43384673e-02,
          1.90518171e-01,  1.33379489e-01,  5.11651561e-02,
         -2.83142298e-01,  1.79980844e-01, -2.93412339e-02,
          1.22310415e-01,  1.26230314e-01,  1.68219343e-01,
          2.24933505e-01],
        [ 1.17071979e-02, -3.95249724e-02, -3.10961176e-02,
         -1.31895971e-02, -3.55200060e-02,  3.91672924e-03,
         -4.87674288e-02,  2.98910998e-02, -1.58856716e-02,
         -6.92862347e-02,  1.10866791e-02, -2.47967727e-02,
          1.21225500e-02,  4.28927224e-03,  2.83624157e-02,
         -5.75982146e-02],
        [ 1.64948441e-02,  1.89197548e-02,  2.86171562e-03,
          1.54470967e-03,  1.04306368e-02,  6.94706291e-03,
         -7.16631040e-02, -1.23474590e-01, -4.22388390e-02,
         -8.56672451e-02, -1.15338877e-01,  4.52852510e-02,
         -1.82628483e-02, -6.57654926e-02,  3.79175437e-03,
          1.27082333e-01],
        [-2.2438442

In [18]:
len(pesos0)

2

In [19]:
len(pesos0[1])

16

In [20]:
len(pesos0[0])

30

In [21]:
pesos1 = neural_network.layers[1].get_weights()
pesos1

[array([[-1.49977580e-02,  1.71617419e-03, -2.63521820e-03,
          2.81959660e-02, -1.23591051e-02, -3.70415226e-02,
         -3.98953333e-02, -3.72231118e-02,  2.60520317e-02,
         -4.61649559e-02, -4.45252657e-02,  4.29146551e-02,
         -3.35419066e-02,  4.64681871e-02,  3.40677239e-02,
         -5.41220978e-03],
        [-2.51892563e-02,  1.30731342e-02,  2.38131769e-02,
         -4.03510146e-02, -2.76576728e-04,  2.00032033e-02,
         -1.21727809e-02,  1.40838362e-02,  8.37385654e-04,
          1.23338588e-02, -4.84474413e-02,  4.82638814e-02,
         -4.92356680e-02, -1.86355431e-02,  5.80314174e-03,
         -2.32131239e-02],
        [-2.48987675e-02,  4.51453142e-02, -2.86479238e-02,
         -2.55824458e-02,  2.59490535e-02, -4.64472659e-02,
         -6.55784458e-03, -1.59169436e-02,  8.79392028e-05,
         -1.65333482e-03, -1.73357129e-02, -1.58602558e-02,
         -5.52597754e-02,  4.95410822e-02, -5.68022989e-02,
         -4.66467030e-02],
        [-3.0012656

In [22]:
pesos2 = neural_network.layers[2].get_weights()
pesos2

[array([[-0.57495064],
        [ 0.63598746],
        [ 0.59110403],
        [-0.07201344],
        [ 0.34363237],
        [ 0.17822182],
        [ 0.2832386 ],
        [ 0.49523818],
        [ 0.47170055],
        [ 0.19167739],
        [-0.18098833],
        [-0.07723601],
        [-0.15437229],
        [ 0.88545305],
        [-0.3903395 ],
        [ 0.50532854]], dtype=float32),
 array([-0.24930736], dtype=float32)]

In [23]:
previsoes = neural_network.predict(X_test)
previsoes = previsoes > 0.5
previsoes

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [

In [24]:
y_test

Diagnosis
512          1
457          0
439          0
298          0
37           0
..         ...
236          1
113          0
527          0
76           0
162          1

[143 rows x 1 columns]

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [26]:
accuracy_score(y_test, previsoes)

0.9230769230769231

In [27]:
confusion_matrix(y_test, previsoes)

array([[89,  1],
       [10, 43]])

In [28]:
neural_network.evaluate(X_test, y_test)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - binary_accuracy: 0.9140 - loss: 0.3738  


[0.3064132630825043, 0.9230769276618958]